# Generated by Django 3.2.25 on 2025-09-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_billingdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingDetail',
        ),
    ]
