# Generated by Django 3.2.25 on 2025-09-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_billingdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetail',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
